version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(funcName)s() - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  # JSON formatter only if python-json-logger is available
  json:
    (): pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
  
  file_error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  file_info:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    filename: logs/info.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  file_debug:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/debug.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8

loggers:
  certify_studio:
    level: DEBUG
    handlers: [console, file_info, file_error, file_debug]
    propagate: false
  
  uvicorn:
    handlers: [console, file_info]
    level: INFO
    propagate: false
  
  uvicorn.error:
    level: INFO
    handlers: [console, file_error]
    propagate: false
  
  uvicorn.access:
    handlers: [console, file_info]
    level: INFO
    propagate: false

root:
  level: INFO
  handlers: [console, file_info, file_error]
